#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────
# StellarPredict — full Testnet deployment
#
# Deploys: mock USDC (SEP-41) → Oracle Registry (+ feeds) → uploads market &
# token wasm → Factory (initialized). Writes all addresses to .env.deployed.
#
# Prereqs:
#   - Stellar CLI (`stellar`) installed and on PATH
#   - A funded identity:  bash scripts/setup-testnet.sh deployer
#
# Usage:  bash scripts/deploy.sh [identity]
# ─────────────────────────────────────────────────────────────────────────
set -euo pipefail

IDENTITY="${1:-deployer}"
NETWORK="testnet"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WASM_DIR="$ROOT/target/wasm32v1-none/release"
OUT="$ROOT/.env.deployed"

# Resolve CLI (soroban was renamed to stellar).
if command -v stellar >/dev/null 2>&1; then CLI="stellar"
elif command -v soroban >/dev/null 2>&1; then CLI="soroban"
else echo "❌ Stellar CLI not found" >&2; exit 1; fi

ADMIN="$($CLI keys address "$IDENTITY")"
echo "▶ Deployer/admin: $ADMIN"

# Helpers ────────────────────────────────────────────────────────────────
deploy() { # <wasm>
  $CLI contract deploy --wasm "$1" --source "$IDENTITY" --network "$NETWORK" 2>/dev/null
}
upload() { # <wasm>  → wasm hash
  $CLI contract upload --wasm "$1" --source "$IDENTITY" --network "$NETWORK" 2>/dev/null
}
invoke() { # <contract_id> <args...>
  local id="$1"; shift
  $CLI contract invoke --id "$id" --source "$IDENTITY" --network "$NETWORK" -- "$@"
}

# 1. Build wasm (host-compatible target) ──────────────────────────────────
# NOTE: factory is built in a SEPARATE cargo invocation from market. In one
# invocation Cargo unifies features, which would turn on market's `contract`
# feature for the factory too and link the Market's wasm exports into
# factory.wasm (shadowing the factory's own `initialize`). Separate invocations
# resolve features independently, so factory links market with `contract` off.
echo "▶ Building leaf contracts + market (wasm32v1-none)…"
( cd "$ROOT" && cargo build --target wasm32v1-none --release \
    -p oracle_registry -p yes_token -p no_token -p lp_token -p market )
echo "▶ Building factory (wasm32v1-none)…"
( cd "$ROOT" && cargo build --target wasm32v1-none --release -p factory )

# 2. Real USDC (Circle's USDC as a Stellar Asset Contract — NO mock token) ─
# We settle in genuine Circle USDC, not a freely-mintable stand-in. The asset's
# SAC id is derived deterministically from USDC:<issuer> + the network. Ensure
# the SAC wrapper exists (idempotent — "already exists" is fine).
#   Testnet issuer: GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5
#   Mainnet issuer: GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN
USDC_ISSUER="${USDC_ISSUER:-GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5}"
USDC_ASSET="USDC:$USDC_ISSUER"
echo "▶ Resolving real USDC asset contract ($USDC_ASSET)…"
$CLI contract asset deploy --asset "$USDC_ASSET" --source "$IDENTITY" --network "$NETWORK" 2>/dev/null || true
USDC="$($CLI contract id asset --asset "$USDC_ASSET" --network "$NETWORK")"
echo "  USDC = $USDC (real Circle USDC SAC)"

# 3. Oracle Registry ──────────────────────────────────────────────────────
echo "▶ Deploying Oracle Registry…"
ORACLE="$(deploy "$WASM_DIR/oracle_registry.wasm")"
invoke "$ORACLE" initialize --admin "$ADMIN" --staleness_threshold 3600
for FEED in XLM_USD_PRICE BTC_USD_PRICE ETH_USD_PRICE; do
  invoke "$ORACLE" register_feed --feed_id "$FEED" --description "$FEED" --decimals 7
done
# Approve the deployer as an oracle operator for testing.
invoke "$ORACLE" set_operator --operator "$ADMIN" --approved true
echo "  ORACLE = $ORACLE"

# 4. Upload market + token wasm (for Factory to clone) ────────────────────
echo "▶ Uploading market & token wasm…"
MARKET_HASH="$(upload "$WASM_DIR/market.wasm")"
TOKEN_HASH="$(upload "$WASM_DIR/yes_token.wasm")"
echo "  MARKET_HASH = $MARKET_HASH"
echo "  TOKEN_HASH  = $TOKEN_HASH"

# 5. Factory ──────────────────────────────────────────────────────────────
echo "▶ Deploying Factory…"
FACTORY="$(deploy "$WASM_DIR/factory.wasm")"
# Struct args are passed as JSON. Fees: 2% trade, 10% protocol share; 1 USDC
# creation fee, 10 USDC min initial liquidity (sized for the 20 USDC/2h faucet).
CONFIG=$(cat <<JSON
{
  "admin": "$ADMIN",
  "oracle_registry": "$ORACLE",
  "protocol_treasury": "$ADMIN",
  "usdc_token": "$USDC",
  "market_creation_fee": "10000000",
  "trading_fee_rate": "200",
  "protocol_fee_share": "1000",
  "min_initial_liquidity": "100000000",
  "max_single_trade_pct": "1000",
  "market_wasm_hash": "$MARKET_HASH",
  "token_wasm_hash": "$TOKEN_HASH"
}
JSON
)
invoke "$FACTORY" initialize --config "$CONFIG"
echo "  FACTORY = $FACTORY"

# 6. Persist addresses ────────────────────────────────────────────────────
cat > "$OUT" <<ENV
# Generated by scripts/deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
STELLAR_NETWORK=$NETWORK
ADMIN_ADDRESS=$ADMIN
USDC_TOKEN_ADDRESS=$USDC
USDC_ISSUER=$USDC_ISSUER
ORACLE_REGISTRY_ADDRESS=$ORACLE
FACTORY_ADDRESS=$FACTORY
MARKET_WASM_HASH=$MARKET_HASH
TOKEN_WASM_HASH=$TOKEN_HASH
ENV

echo ""
echo "✅ Deployment complete → $OUT"
echo "   USDC settles in REAL Circle USDC — fund accounts via the testnet faucet"
echo "   (https://faucet.circle.com) and add a USDC trustline before creating markets."
